config/routes.rb
Rails.application.routes.draw do
  root :controller => 'projects', :action => 'index'

  get 'users/index'

  resources :projects

  scope "/:name" do
    get "/" => "projects#show"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, uniqueness: true
  validates :name, presence: true

  has_many :project

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :allow_cross_domain_access
  def allow_cross_domain_access
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "*"
  end
end

app/controllers/projects_controller.rb
require 'json'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  protect_from_forgery except: :create

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if params[:name]
      @project = Project.where(name: "#{params[:name]}").first
    else
      set_project
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create

    begin

      if params[:access_token]
      #   # get name and email by GitHub API with access_token
        client = Octokit::Client.new(access_token: params[:access_token])
        user = client.user
        name = user.login

        # if user with this name not exists...
        @user = User.where(name: name).first
        if @user.blank?
          @user = User.create(name: name)
        end

        project_json = JSON.parse(params[:project])
        project_name = project_json['name']
        project_data = JSON.pretty_generate(project_json['data'])

        @project = @user.project.build(name: project_name, data: project_data)
        @project.name = @project.name.delete(" ")

        # JSON.parse project data and create nodes and links
        # nodes -> node_ids, links -> link_ids
        # check if node and link already exists
        # (node unique parameter : name && author && year)
        # (link unique parameter : refering node id && referred node id)
        # create node and link only when it not exists
        # update node_ids and link_ids

        if @project.save # auto check if project uniqueness ?
          @success = true
        else
          @success = false
        end
      else
        @success = false
      end
    rescue => e
      @success = false
    end

  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :data)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paper Tree Project</title>
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <style>
    html,body {
      height: 100%;
      margin: 0;
      background-color: #E5E5E5;
    }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, :remote=>true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/create.html.erb
<div id="test">aaaaaaaa</div>
<script>
  var url = document.referrer;
  <% if @success %>
    url = url + "?project=<%= @name %>";
  <% else %>
    url = url + "?error=1";
  <% end %>
  document.getElementById("test").innerHTML = url;
  location.href = url;
</script>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/rhombus-list/rhombus-list.html">

<style>
  @font-face {
    font-family: "Monterey";
    src: url(../font/Monterey.ttf);
  }
</style>

<style>
  html, body {
    width: 100%;
    margin: 0;
    padding: 20px 0;
    background: #607d8b;
  }
  rhombus-list#nav {
    width: 100%;
    position: absolute;
    top: 30px;
  }
  rhombus-list#title {
    width: 100%;
    position: absolute;
    top: 180px;
  }
  rhombus-list#projects {
    width: 100%;
    position: absolute;
    top: 450px;
  }

  rhombus-list /deep/ span {
    color: #ECEFF1;
  }
  rhombus-list /deep/ .parts {
    border-color: #CFD8DC;
  }
  rhombus-list /deep/ .parts:hover span {
    color: #37474F;
  }
  rhombus-list /deep/ .parts:hover {
    background-color: #FFFF8D;
  }

  rhombus-list#title /deep/ span {
    font-size: 45px;
    font-family: 'Monterey';
  }
  rhombus-list#title /deep/ .parts {
    border-style: dotted;
  }
  rhombus-list#title /deep/ .parts:hover span {
    color: #ECEFF1;
  }
  rhombus-list#title /deep/ .parts:hover {
    background-color: transparent;
  }
</style>


<rhombus-list id="nav" side="120" border="2" num="2"></rhombus-list>

<rhombus-list id="title" side="150" border="1" num="3"></rhombus-list>

<rhombus-list id="projects" side="75" border="2" num="6"></rhombus-list>

<script>
  document.querySelector("rhombus-list#nav").data = [
    {text: "About", url: "https://github.com/sosuke-k/paper-tree-client/wiki/Paper-Tree-Project"},
    {text: "Download", url: "https://github.com/sosuke-k/paper-tree-client/releases"}
  ];
  document.querySelector("rhombus-list#title").data = [
    {text: "Paper", url: "http://papertree.unzoning.com/"},
    {text: "Tree", url: "http://papertree.unzoning.com/"},
    {text: "Project", url: "http://papertree.unzoning.com/"}
  ];
  document.querySelector("rhombus-list#projects").data = [
  <% @projects.each do |project| %>
    {text: "<%= project.name %>", url: "/<%= project.name %>"},
  <% end %>
  ];
</script>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<script src="../bower_components/webcomponentsjs/webcomponents.js"></script>
<link rel="import" href="../custom_components/doc-graph-application.html">

<doc-graph-application name="<%= @project.name + ' made by ' + @project.user.name %>" data="<%= @project.data %>"></doc-graph-application>

app/views/users/index.html.erb
<h1>Users#index</h1>
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>